services:
  builder:
    build: .
    volumes:
      - site-data:/app/_site
    env_file:
      - .env
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "3000:80"
    volumes:
      - site-data:/usr/share/nginx/html:ro
    depends_on:
      - builder
    restart: unless-stopped

volumes:
  site-data:
